

export const data = [
  {
    "name": "Humitas",
    "description": "La Humita en chala, es un cocido de maíz rallado con cebolla, pimientos, tomates y especias que forman una pasta envuelta en la hoja del choclo (chala) y luego es cocida al vapor o agua hirviendo. Se trata de una de las comidas tradicionales de Jujuy, de alto valor nutritivo y es una de las más populares sobre todo en Semana Santa.",
    "ingredients": [
      "10 choclos",
      "3 cebollas",
      "1 pimiento rojo",
      "1 pimiento verde",
      "2 cebollas de verdeo",
      "1 cdta. de manteca",
      "2 litros de agua",
      "1/2 taza de leche",
      "300 gramos de queso",
      "Sal y pimienta a gusto",
      "1 cdta. de azucar"
    ],
    "preparation": [
      "Paso 1:",
      "Retirar las chalas de los choclos con cuidado, a fin de ser blanqueada en agua hirviendo con sal. Luego de unos minutos, la chala debe ser retirada del agua, escurrida y cortada en tiras, para ser utilizada más adelante.",
      "Paso 2:",
      "Rallar los choclos y reservarlos en un tazón, así como picar todos los ingredientes detallados.",
      "Paso 3:",
      "Poner la manteca en una sartén, agregar la cebolla blanca, la cebolla de verdeo (reservar la parte verde para agregar al final) y los pimientos. Rehogar (freír ligeramente) por unos minutos.",
      "Paso 4:",
      "Una vez que los ingredientes estén dorados, agregar el choclo rallado y el tomate picado.",
      "Paso 5:",
      "Cocinar unos minutos y agregar la leche, una cucharadita de azúcar, sal y pimienta al gusto.",
      "Paso 6:",
      "Una vez que la consistencia de la preparación sea cremosa, retirar del fuego y dejar enfriar.",
      "Paso 7:",
      "Colocar dos tiras de chala en forma de cruz.",
      "Paso 8:",
      "Poner en el centro un poco de relleno.",
      "Paso 9:",
      "Colocar por encima unos daditos de queso fresco.",
      "Paso 10:",
      "Cerrar el paquete y atarlo muy bien con un hilo. De esta forma armar todos los paquetes.",
      "Paso 11:",
      "Una vez listos, preparar una olla con agua hirviendo y sal, agregar los paquetes dentro y cocinar alrededor de 20 o 25 minutos."
    ],
    "time": "60",
    "image": ""
  },
   {
    "name": "Tamales",
    "description": "El tamal es un platillo típico similar a las humitas.Consiste en una pasta de choclo(maíz) envuelta en las hojas del choclo, con la diferencia de que el tamal viene relleno con carne tipo charqui, cebolla y algunos condimentos.",
    "ingredients": [
      "1 kilogramo de Harina de maíz",
      "500 gramos de Zapallo",
      "1 kilogramo de Carne de vaca",
      "200 gramos de Grasa de cerdo o vaca",
      "2 Pimientos colorados",
      "250 gramos de Cebolla",
      "Pimentón",
      "Comino",
      "1 pizca de Pimienta",
      "Ají picante",
      "Agua",
      "1 pizca de Sal",
    ],
    "preparation": [
      "Paso 1:",
      "Cocinar en abundante agua hirviendo la harina de maíz junto con el zapallo cortado en trozos pequeños, mezclando constantemente con cuchara de madera. Condimentas con sal. Debe quedar firme.",
      "Paso 2:",
      "Para preparar el relleno rehogas en grasa caliente la cebolla y los pimientos, cortados en trocitos. Agregas la carne cortada en cubitos o en tiras pequeñas. Condimentas con sal, pimienta, pimentón, comino y ají picante. Una vez cocinado  agregas los huevos duros cortados en cubitos.",
      "Paso 3:",
      "Sobre una chala previamente limpia y hervida, extiendes una capa rectangular de la preparación realizada con harina de maíz y zapallo; sobre ella  colocas el relleno y otra capa de la preparación mencionada. Envuelves formando paquetitos que se atan con piolín o con tiritas cortadas de la chala."
    ],
    "time": "60",
    "image": "https://descubrirturismo.com/wp-content/uploads/2019/01/12932979_10153676457954102_3740663838310989977_n.jpg"
  },
  {
    "name": "Empanadas",
    "description": [
      "La empanada es uno de los platillos más tradicionales y típicos de la provincia. Se trata de un pastel relleno con carne picada, cebolla, ajo, pimentón, aceite y otros ingredientes, que se envuelve en una masa y se cocina al horno o bien se hace frita.",
      "La principal característica diferenciadora de la empanada jujeña es la inclusión de papa en su relleno."
    ],
    "ingredients": [
      "500 gramos Carne Molida o Carne Picada en trocitos (vaca o pollo)",
      "250 gramos Cebolla Picada en cubos",
      "30 gramos Pimentón",
      "500 gramos papa Hervida picada en cubos",
      "2 Huevos Hervidos rallados",
      "100 gramos Cebollina de verdeo picada en cubos",
      "100 gramos Arveja cocida o Lata de arveja",
      "2 tomates rallados",
      "Sal a gusto",
      "350 gramos Harina 0000",
      "500 gramos Grasa Vacuna",
      "500 ml Agua con sal (Salmuera)",
      "250 gr Manteca"
    ],
    "preparation": [
      "Paso 1:",
      "Preparación de la Masa: En un recipiente colocar a fuego lento la Grasa y dejar derretir. Y preparar agua tibia con 2 cucharas de sal.",
      "Paso 2:",
      "Volcar la harina en una superficie limpia y hacer un centro, en él colocar la grasa derretida y de a poco incorporar el agua tibia, mientras vamos amasando. Después dejarlo reposar unos 20 minutos, mientras preparamos el recado (Relleno de la empanada).",
      "Paso 3:",
      "Luego de los 20 minutos transcurridos, estirar la masa y cortar en discos a gusto.",
      "Paso 4:",
      "Preparación del recado (relleno): en un recipiente colocar a fuego lento, una cuchara de aceite e incorporar la cebolla picada en cubos e ir mezclando hasta dorar los ingredientes. Y luego colocar la Carne picada o molida y una cucharadita de Pimentón, sal y revolver todo hasta su media cocción, es decir no debe estar completamente cocida la carne.",
      "Paso 5:",
      "Por otro lado retiramos la cáscara de la papa y trozamos en cubos, colocando en un recipiente previo Agua hervida con sal a gusto por 10 a 12 minutos controlados. Luego colar y reservar aparte. (No tirar el agua o caldo de la Papá hervida, pues servirá para colocar cucharitas en el recipiente donde se está haciendo la cebolla y la carne del paso anterior).",
      "Paso 6:",
      "En un recipiente medianamente profundo, colocar la papa cocida en cubos, La cebolla de verdeo picada, el huevo duro rallado, la preparación de la cebolla, la carne y la arveja (mezclar todo).",
      "Paso 7:",
      "Tomamos los discos de empanadas y armamos colocando el recaudo y haciendo los rulitos a gusto propio.",
      "Paso 8:",
      "EMPANADAS AL HORNO: Preparar una asadera aceitada o engrasada, colocar las empanadas ya armada, y luego aparte rompemos un huevo lo batimos y con dicho líquido pintamos por encima de la empanada para darle ese brillo característico de la empanada (opcional), luego metemos a Fuego en horno previamente calentando o bien en horno de barro que sale más sabrosito.",
      "Paso 9:",
      "EMPANADAS FRITAS: En un Recipiente colocar aceite y calentarlo, luego incorporar las empanadas de a poco y dar vueltas, hasta su cocción y luego reservar en un recipiente con servilletas o papel absorbente de aceite (La cantidad de aceite debe tapar la empanada para una mejor cocción).",
    ],
    "time": "90",
    "image": "https://www.lavoz.com.ar/resizer/uU_CcXw2TkpWfgAMMPKWV0ZZji0=/1024x683/smart/filters:quality(75):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/RS5SCAH6HZAR5IAXSTBKI3VZ3E.jpg"
  },
  {
    "name": "Locro",
    "description": [
      "El locro es uno de los platos estrella de la gastronomía jujeña. Esta comida típica de Jujuy se elabora a base de maíz o trigo molido, el cual se debe dejar en remojo aproximadamente 10 horas. Tradicionalmente se consume de manera masiva en las fechas patrias."
    ],
    "ingredients": [
      "1 Kg. de maíz para locro",
      "1 Kg. de poroto",
      "2 Kg. de queperí",
      "1 Kg. de tripa gorda",
      "2 Kg. de Zapallo (no fibroso)",
      "2 cebollas medianas,",
      "1 pocillo (de té) de aceite,",
      "1 cucharada colmada de sal gruesa,",
      "1 cucharada al ras de comino molido,",
      "1 cucharada colmada de pimentón,",
      "1 cucharada de ají colorado molido,",
      "A gusto: huesos de cerdo, cuero de cerdo, chorizo español, panceta, cebolla de verdeo."
    ],
    "preparation": [
      "Paso 1:",
      "Lavar bien el maíz y el poroto. Dejarlos en remojo la noche anterior en cacerolas separadas.",
      "Paso 2:",
      "Lavar las tripas, darles un hervor de diez a quince minutos, cortarlas en rodajas no gruesas, también lavar los huesos y cuero de cerdo.",
      "Paso 3:",
      "Cortar el queperí en trozos medianos, igualmente el zapallo y el cuero de cerdo.",
      "Paso 4:",
      "Poner a hervir clínico litros de agua, agregar el maíz con el agua de remojo y la cebolla picada menuda, huesos y cuero de cerdo y el queperí. Dejar hervir una hora.",
      "Paso 5:",
      " Luego agregar el poroto con el agua de remojo, las tripas, zapallo, panceta, chorizo, sal gruesa y comino, dejar hervir una hora removiendo continuamente para evitar que se queme o se pegue en el fondo de la cacerola.",
      "Paso 6:",
      "En aceite freír una cebolla picada, agregar el ají, pimentón sal fina a gusto y medio cucharón de agua, dejar hervir hasta que se obtenga una salsa semiespesa.",
      "Paso 7:",
      "Servir colocando en cada plato un poco de salsa y verdeo.",
    ],
    "time": "160",
    "image": "https://www.clarin.com/2022/04/29/hIhovn6Ct_720x0__1.jpg"
  },
  {
    "name": "Picante de Pollo",
    "description": "Liderando la lista de platos regionales preferidos y elegidos tanto por jujeños como por turistas del país y del mundo, está el picante de pollo. Típico alimento de la zona andina que ha fusionado a través de la historia ingredientes de origen hispanos como originarios.",
    "ingredients": [
      "c/n de aceite vegetal",
      "4 presas de pollo con piel a elección",
      "Sal y pimienta negra molida a gusto",
      "3 cebollas",
      "5 tomates",
      "1 pimiento rojo",
      "1-2 ajíes amarillos",
      "1 cdta. de comino",
      "1 cdta. de orégano",
      "1 taza de arvejas",
      "2 tazas de caldo de pollo",
      "400 g de chuño",
      "3 huevos",
      "2 cdas. de queso rallado",
      "2 papas",
      "1 cebolla morada",
      "200 g de arroz",
      "Maní molido y cocido (opcional)",
      "Azafrán (opcional)",
      "1 puñado de perejil"
    ],
    "preparation": [
      "Paso 1:",
      "En un sartén caliente con suficiente aceite dorar bien el pollo por ambos lados, retirar del fuego y reservar.",
      "Paso 2:",
      "En el mismo sartén rehogar 2 cebollas picadas finamente, por otra parte licuar o procesar 4 tomates sin semillas, el pimiento rojo sin semillas ni venas, el ají amarillo, el comino, el orégano, incorporarlo al sartén cuando las cebollas estén bien rehogadas y cocinar unos dos minutos.",
      "Paso 3:",
      "Incorporar ½ taza de caldo, las presas de pollo, bajar el fuego y continuar la cocción con el sartén tapado.",
      "Paso 4:",
      "Por otra parte picar una cebolla y rehogarla con un poco de aceite, agregar el chuño previamente remojado, lavado y picado, cocinar un poco e incorporar los huevos removiendo un poco, agregar queso rallado y el maní si se desea, salpimentar y reservar caliente.",
      "Paso 5:",
      "Controlar que la salsa del pollo no se seque, y que el pollo se haya cocido bien, si es necesario agregar más caldo, incorporar las arvejas en los últimos cinco minutos de cocción.",
      "Paso 6:",
      "Hervir las papas, picar el tomate en rodajas y la cebolla en pluma. Cocinar el arroz blanco o con azafrán si se desea.",
      "Paso 7:",
      "Servir en cada plato una presa de pollo bañado con la salsa, el revuelto de chuño, media papa hervida, un poco de tomate en rodajas y cebollas en julianas, el arroz y perejil picado.",
    ],
    "time": "90",
    "image": "https://pbs.twimg.com/media/DjnqLSdXsAAZASl.jpg"
  },
]